services:
  # Jellyfin - Media Server
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - media_net
      - proxy_net
    volumes:
      - ${DATA_ROOT}/configs/jellyfin:/config
      - ${DATA_ROOT}/media/tv:/data/tv
      - ${DATA_ROOT}/media/movies:/data/movies
      - ${DATA_ROOT}/media/books:/data/books
      - ${DATA_ROOT}/downloads:/data/downloads
    restart: unless-stopped

 # Jellyseerr - Request Management
  # jellyseerr:
  #   image: fallenbagel/jellyseerr:latest
  #   container_name: jellyseerr
  #   networks:
  #     - media_net
  #   environment:
  #     - LOG_LEVEL=info
  #     - TZ=${TZ}
  #     - PORT=5055
  #   volumes:
  #     - ${DATA_ROOT}/configs/jellyseerr:/app/config
  #   restart: unless-stopped

networks:
  media_net:
    external: true
  proxy_net:
    external: true