name: nginx-proxy-manager

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'      # HTTP
      - '443:443'    # HTTPS
      - '81:81'      # Admin UI
    volumes:
      - ${APPDATA_ROOT}/nginx-proxy-manager/data:/data
      - ${APPDATA_ROOT}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    environment:
      - TZ=Pacific/Auckland
    networks:
      - proxy_net
      - internal_net
  openclaw-tunnel:
    image: alpine:3.20
    container_name: openclaw-tunnel
    restart: unless-stopped
    command: 
      - sh
      - -c
      - |
          apk add --no-cache openssh-client
          cp /ssh-src/openclaw_lab_tunnel /tmp/openclaw_lab_tunnel
          chmod 600 /tmp/openclaw_lab_tunnel
          exec ssh -NT \
            -o ExitOnForwardFailure=yes \
            -o ServerAliveInterval=30 \
            -o ServerAliveCountMax=3 \
            -o StrictHostKeyChecking=accept-new \
            -o BatchMode=yes \
            -i /tmp/openclaw_lab_tunnel \
            -L 0.0.0.0:18789:127.0.0.1:18789 \
            oli@192.168.1.16
    volumes:
       - /home/oli/.ssh/openclaw/openclaw_lab_tunnel:/ssh-src/openclaw_lab_tunnel:ro
    networks:
      - proxy_net

networks:
  proxy_net:
    name: proxy_net
    external: true
  internal_net:
    name: internal_net
    external: true
